### ISSUE TITLE
Drag event on `.tab-content` not bubbled to `.tab`

### ISSUE THREAD

**Issue by jcuenod** [mathuo/dockview#102]
If you try to drag the title of a tab (the `.tab-content` element), nothing will happen. You have to drag on the margin around `.tab-content`. I believe the reason is that it's not propagated to the `.tab` element.

I'm using Firefox 100.0b9 (on Arch)

**Comment by mathuo** [comment]
I see the same bug - will take a look

**Comment by mathuo** [comment]
This is an example using a version publish on npm under an experimental tag https://www.npmjs.com/package/dockview/v/0.0.0-experimental-a7b05cf1-20220509 which should allow dragging of the tab from any postion in Firefox

https://codesandbox.io/s/dockview-firefox-issue-7hsjj8?file=/src/app.tsx

Will most likely publish in the next few days once all is confirmed to work.
