### ISSUE TITLE
Ability to drag tabs into empty panels.

### ISSUE THREAD

**Issue by abalter** [mathuo/dockview#163]
Is it possible to configure an empty panel so that you can drag a tab into it?

![image](https://user-images.githubusercontent.com/5349876/205479173-43f740e3-e708-454f-983c-b05238341eab.png)

**Comment by mathuo** [comment]
Currently, no. Would it be useful if it did accept a panel?

**Comment by abalter** [comment]
If I could then drag tabs into that, that would be great!
