### ISSUE TITLE
Minimized & floating tabs

### ISSUE THREAD

**Issue by jccq** [mathuo/dockview#165]
Hi it would be great to have support of minimixing tabs (a la gmail minimized email) and for floating windows as well (with an option to return to the tab they were detached from).

Is it possible to sponsor the project somehow?

**Comment by mathuo** [comment]
**_Update_**

Experimental floating groups are a work in progress, currently here https://github.com/mathuo/dockview/issues/230. Will most likely take a look too at minimized tabs since I 'think' that functionality should mostly fall out of the work done to have floating groups.
