### ISSUE TITLE
Window Preview stuck on top layer

### ISSUE THREAD

**Issue by m-ephraim** [mathuo/dockview#166]
The window preview that shows when hovering over a window in DockView (with the blue border) gets stuck on the screen sometimes:

![image](https://user-images.githubusercontent.com/7613303/208733337-59721bf4-74ee-42ff-85b5-d3f51669a3ab.png)

It seems to happen when the dock view popup is open over a dock icon, and I mouse over and through that popup quickly and click into an open app on the screen.  Once it is in this state, the window preview stays on top and can't be removed, even quitting the app related to the stuck preview won't get rid of the stuck preview.  The only way to get rid of it is to Quit the DockView app.

Running:
DockView Version 1.3 (130)
maxOS Monterey 12.6.1
MacBook Pro 16-inch
Apple M1 Pro Chip

**Comment by mathuo** [comment]
Sorry, not the right application. This repository is for a TypeScript UI library component, not associated with Apple.
