### ISSUE TITLE
Activation Delay continues after no longer over dock icon

### ISSUE THREAD

**Issue by m-ephraim** [mathuo/dockview#167]
The delay timer for the dock view preview seems to continue, even after the mouse has long left the dock icon.  For example, in this video, the mouse just travels quickly through the Finder icon and the DockView preview pops up long after the mouse has left hovering over the Finder icon:

![Screen Recording 2022-12-20 at 12 46 59 PM](https://user-images.githubusercontent.com/7613303/208743987-b6bbcd7a-3020-48a7-a1e6-cd0068e0982b.gif)

Running:
DockView Version 1.3 (130)
maxOS Monterey 12.6.1
MacBook Pro 16-inch
Apple M1 Pro Chip

**Comment by mathuo** [comment]
Sorry, not the right application. This repository is for a TypeScript UI library component, not associated with Apple.
