### ISSUE TITLE
DockviewApi.toJSON doesn't include panel titles

### ISSUE THREAD

**Issue by alakhpc** [mathuo/dockview#258]
Hi, I absolutely love the work you're doing with this library :), and am trying to use it.

**Describe the bug**
I think I've run into a bug where the panel title is not included in the JSON, causing the title to reset to the id when you refresh (persistent layout).

1. Create a panel with a title, the panel renders with the correct title.
2. Check `DockviewApi.toJSON()`
4. See blank title

**Expected behavior**
Expected title to be included in the JSON

```json
{
   "id":"xlfqnma9wioq948mmf6mh7u2",
   "contentComponent":"heatmap",
   "params":{
      "title":"Heatmap"
   },
   "title":""
}
```

**Comment by mathuo** [comment]
Thank you and thanks for the report. Which version are you using?

I have an example here using the latest version **1.7.2** which seems to persist and reload a custom panel title but I may be missing something. You might be able to adjust my example to "break it"?

https://codesandbox.io/p/sandbox/github/mathuo/dockview/tree/master/packages/docs/sandboxes/layout-dockview

**Comment by alakhpc** [comment]
I think I've narrowed it down.
It seems to happen only when I have a title, and a prop called title.

```ts
  api.addPanel({
    id: "panel_1",
    component: "default",
    // title here 
    title: "Heatmap",
    params: {
      // title here also
      title: "Heatmap",
    },
  });
```

Reproducible codesandbox:
view link: https://lnz49u-3000.csb.app/

https://codesandbox.io/p/sandbox/stoic-napier-lnz49u?file=%2Fsrc%2Fapp.tsx%3A26%2C1-33%2C6

1. Click reset Layout, title of panel_1 should be `Heatmap`
2. Refresh, title changes to `panel_1`

https://github.com/mathuo/dockview/assets/36898190/22b73b73-5ce4-4885-85ee-8dcc1ed85b21

**Comment by mathuo** [comment]
Sandbox example using the build created from this branch as evidence of a working fix.

https://codesandbox.io/s/layout-dockview-forked-2nfmmq

**Comment by alakhpc** [comment]
That seems great!

**Comment by mathuo** [comment]
1.7.3 published with fix - thanks for the help in finding the bug

**Comment by alakhpc** [comment]
I think I've discovered another related bug:

If I use `api.updateParameters` inside a panel, it resets the title, even though the original title was not in the params

**Comment by mathuo** [comment]
Damn, sorry yeah I see this - seems to be an existing bug again. I will take a deeper look at this logic and add tests.

**Comment by mathuo** [comment]
Sandbox example using a copy that has these changes https://github.com/mathuo/dockview/pull/265 [here](https://codesandbox.io/s/constraints-dockview-forked-ih989q?file=/src/app.tsx).

Shows examples of both `api.setTitle` and `api.updateParameters` being used and covering the case where somebody may name a custom parameter `title`.

Looks good to me currently, will take some more checks too.

**Comment by alakhpc** [comment]
I think I'm still seeing the bug, gonna try and make a sandbox

**Comment by alakhpc** [comment]
My bad, just had to clean node_modules.

Looks good, Thanks!

**Comment by mathuo** [comment]
v.1.7.4 published with fixes
