### ISSUE TITLE
Access to DataTransfer object on drag events

### ISSUE THREAD

**Issue by mathuo** [mathuo/dockview#299]
- Would it be possible to add support to the API of the dock panel tab and group for setting the `DataTransfer`? I have a use case where the tab represents a file, and the group is a directory, and dragging the tab or group onto an input, I need to be able to specify the value of the `DataTransfer` object on the drag handler.

  I've tried my own stab at it, but I have difficulty figuring out how the `Tab` objects are created in relation to the tab component.

_Originally posted by @techbech in https://github.com/mathuo/dockview/issues/298#issuecomment-1634048922_

**Comment by mathuo** [comment]
@techbech Just initial thoughts, would something like this work?

```tsx
interface DragPanelEvent {
    panel: IDockviewPanel;
    nativeEvent: DragEvent;
}

interface DragPanelEvent {
    group: IDockviewGroupPanel;
    nativeEvent: DragEvent;
}

api.onWillDragPanel((event: DragPanelEvent) => { /** */ })

api.onWillDragGroup((event: DragPanelEvent) => { /** */ })
```

**Comment by techbech** [comment]
Thank you!

I noted that `dataTransfer` [is read-only,](https://developer.mozilla.org/en-US/docs/Web/API/DragEvent#instance_properties) but I guess it will still work.

Just expanding on yours. Is the following how I would use it?

```typescript
interface DragPanelEvent {
    panel: IDockviewPanel;
    nativeEvent: DragEvent;
}

interface DragGroupEvent {
    group: IDockviewGroupPanel;
    nativeEvent: DragEvent;
}

event.api.onWillDragPanel(({panel, nativeEvent}: DragPanelEvent) => {
    if (panel.params.filePath) {
        nativeEvent.setData("text/plain", panel.params.filePath);
    }
})
event.api.onWillDragGroup(({group, nativeEvent}: DragGroupEvent) => {
    if (group.params.directoryPath) {
        nativeEvent.setData("text/plain", "my-directory/");
    }
})
```

That would be awesome! And it will also work with serialize/deserialize, right?

**Comment by techbech** [comment]
Awesome!

I just played around and found the `updateParameters(...)` method on the group. But it's fine in my case to get the data from elsewhere.

Let me know if you could use any help or could use someone to discuss things with.
