### ISSUE TITLE
Add back suppressClosable param or remove from docs 

### ISSUE THREAD

**Issue by Imbozter** [mathuo/dockview#319]
Looking at the Git history, it seems as though the `suppressClosable` param was removed from the dockview panel API, but is still listed as available in the docs. Could this please be added back as a feature or if not, removed from the docs? 

This seems like it would be a fairly common use case, I'm not sure why it was removed. 

It would be good if there was a parameter that allowed users to remove the ability to close tabs without having to make a custom tab header component, as this seems like a lot of effort for a small change. 

BTW, great library, super performant :)

**Comment by mathuo** [comment]
Thank you for fixing the docs @Imbozter
