### ISSUE TITLE
Add 'hideClose' to DockviewDefaultTab component

### ISSUE THREAD

**Issue by mathuo** [mathuo/dockview#321]
See suggestions in https://github.com/mathuo/dockview/issues/319

```tsx
import {
  DockviewDefaultTab,
  IDockviewPanelHeaderProps,

} from "dockview";

const defaultHeaderComponent = (props: IDockviewPanelHeaderProps) => {
  return <DockviewDefaultTab {...props} onContextMenu={() => {/** */}} />;
};
```

> Implementation of `DockviewDefaultTab` can be found [here](https://github.com/mathuo/dockview/blob/master/packages/dockview/src/dockview/defaultTab.tsx).

I do think it could be useful to add a prop on `DockviewDefaultTab` such as `hideClose` to make it easier to remove the close buttons using custom tab components without having to worry about an entire component and it's styling though now I think about it so I will look at adding that.

**Comment by techbech** [comment]
I think it's a fine addition as it will not add to the API of a Dockview panel but stay an isolated change to only the default tab component.
