### ISSUE TITLE
Possible to stop floating windows being dragged outside visible dockview area?

### ISSUE THREAD

**Issue by mathuo** [mathuo/dockview#326]
### Discussed in https://github.com/mathuo/dockview/discussions/325

<div type='discussions-op-text'>

<sup>Originally posted by **lexwebb** August 26, 2023</sup>
I'm new to dockview and I've been doing some experimenting in my app. I want to use a mix of floating and docked windows and I've noticed it's possible to drag the floating windows outside of the general dockview area.

Is there a built in way to prevent this behavior, and constrain the dragging of windows to only the Dockview area? I haven't been able to find anything in the docs or issues about it, but i'm happy to be proven otherwise!</div>

**Comment by mathuo** [comment]
@lexwebb something like this behaviour via an input flag?

https://codesandbox.io/s/floatinggroup-dockview-forked-jtp2xq?file=/src/app.tsx

**Comment by lexwebb** [comment]
That's excellent, exactly what I was thinking. Thanks for jumping on this so quick!

**Comment by mathuo** [comment]
Great - I will look at refining this and adding it to the next release. Until then the exact example does exist an as experimental build in npm under version `0.0.0-experimental-91e4e321-20230827` if you did want to download and use it as it.

```
npm install dockview@0.0.0-experimental-91e4e321-20230827
```
