### ISSUE TITLE
Options before tabs start

### ISSUE THREAD

**Issue by mathuo** [mathuo/dockview#338]
### Discussed in https://github.com/mathuo/dockview/discussions/337

<div type='discussions-op-text'>

<sup>Originally posted by **michaelsharpe** September 25, 2023</sup>
Great library!  I am looking to switch over from my current implementation in my app. I have one quick question.  Is there any way to add a custom icon/integration to the left of all the tabs? Below is my current design and I have the menu icon before all the tabs start and would love to implement this with dockview.

<img width="1245" alt="Screenshot 2023-09-24 at 11 33 30 PM" src="https://github.com/mathuo/dockview/assets/2397603/d896c7ac-bcff-4d49-a4f6-4a7761c22baf">

Thanks!

</div>

**Comment by mathuo** [comment]
Example using the Codesandbox PR version here https://codesandbox.io/s/demo-dockview-forked-7hl2f2?file=/src/app.tsx

Naming subject to change but can expect the behaviourto be very similar to this.

![image](https://github.com/mathuo/dockview/assets/6710312/ea0c0e66-5f72-47e4-b51b-7f1f267b6536)

**Comment by michaelsharpe** [comment]
Omg thank you so much!

I am in love with your library btw.  It is so clean and easy to use.  It simplifies so much of my layout issues and gives me a new creative freedom as I build out our tool.

**Comment by mathuo** [comment]
Released in version `1.8.4`
