### ISSUE TITLE
Floating tab groups move in nested dockview

### ISSUE THREAD

**Issue by michaelsharpe** [mathuo/dockview#344]
**Describe the bug**
I am using nested dockviews.  I have one controlling a tab system, and within the tab there are workspaces with tab windows.  When I pop a group out and position it, switch parent tabs, and come back, the floating group is moved to the top right corner.

**To Reproduce**
This issue can be reproduced directly on the nested dockview demo on the site here https://dockview.dev/docs/components/dockview#nested-dockviews.

1. Go to https://dockview.dev/docs/components/dockview#nested-dockviews
2. Move the parent tabs into the same tab bar.
3. Pop out one of the tabs of the child and move it somewhere
5. Switch tabs
6. Return back to tab with nested dockview.

**Expected behavior**
Floating tab groups should stay where they are placed.

**Screenshots**

<video src="https://github.com/mathuo/dockview/assets/2397603/9fc78fd3-f2d9-4c33-9074-aeb944c21a14" controls="controls" style="max-width: 730px;">
</video>

**Desktop (please complete the following information):**

**Additional context**

**Comment by michaelsharpe** [comment]
Thanks for the explanation!  Stoked for this to be working.  This is perhaps one of my favourite features of switching over to Dockview.

Out of curiosity, anything on the roadmap to pull a tab out into a totally new browser window?

**Comment by mathuo** [comment]
Released in version `1.8.4`

**Comment by garyvh2** [comment]
Hey there @mathuo I've ran into an instance of this issue when applying `display: none` on the element containing the view.

Here's a video, not sure if you have any recommendations.

https://github.com/mathuo/dockview/assets/21265830/6e7d6b97-881b-4c85-b706-cc0a9bebc454

**Comment by mathuo** [comment]
> Any answer on @garyvh2 comment? I am seeing the same issue where when you use `display:none`, the library resets the floating windows position to 0,0.

Hey. - can you expand on what exactly you are doing? Slightly usure where the `display: none` is coming from?

**Comment by mathuo** [comment]
> In my case at least, we have a top level utility that works as a tab manager, each tab has an instance of Dockview, when the tab is not selected, the content gets applied `display: none` causing Dockview to recalculate its size over a non rendered view.

ah ok - so in your case you are settings a `display: none` on the entire dockview instance?

**Comment by garyvh2** [comment]
I think is on a div on top of it, but yeah, not sure if there's a workaround to make sure size is preserved when display none is applied.

**Comment by mathuo** [comment]
> I think is on a div on top of it, but yeah, not sure if there's a workaround to make sure size is preserved when display none is applied.

nice, that makes more sense. I have a feeling it's probably something in the [resizable.ts](https://github.com/mathuo/dockview/blob/master/packages/dockview-core/src/resizable.ts) logic. I will need to check how this behaves with `display: none`, will open as a new issue. Thanks

**Comment by garyvh2** [comment]
Much appreciated, Mathuo
