### ISSUE TITLE
Investigate opening tabs in new Browser Window

### ISSUE THREAD

**Issue by mathuo** [mathuo/dockview#360]
Thanks for the explanation!  Stoked for this to be working.  This is perhaps one of my favourite features of switching over to Dockview.

Out of curiosity, anything on the roadmap to pull a tab out into a totally new browser window?

_Originally posted by @michaelsharpe in https://github.com/mathuo/dockview/issues/344#issuecomment-1741828801_

**Comment by mathuo** [comment]
![Animation](https://github.com/mathuo/dockview/assets/6710312/d741a00b-f890-46f5-83b9-e4bad5423a37)

**Comment by michaelsharpe** [comment]
This is so exciting!

**Comment by mathuo** [comment]
@michaelsharpe I've published the current state under an experimental build. I believe this is getting close to a production-grade solution but it may be subject to some change. Any feedback appreicated as always.

```
npm install dockview@0.0.0-experimental-1264055-20231228
```

- The state of popout windows is serialized with the layout.
- A popout window requires a page to utlize, by default this is <host>/**popout.html**. You can specify your own page location which I believe most users will need to do. This page should be a blank .html page.

```tsx
  addPopoutGroup(
      item: IDockviewPanel | DockviewGroupPanel,
      options?: {
          position?: Box;
          popoutUrl?: string;
      }
  ): void;
```

From the primary api

```tsx
api.addPopoutGroup(group);
```

From within a panel

```tsx
props.containerApi.addPopoutGroup(props.api.group);
```

**Comment by michaelsharpe** [comment]
Awesome!!! I'll try it out and let you know how it goes.

**Comment by mathuo** [comment]
Refer to https://github.com/mathuo/dockview/issues/365 for beta builds and documentation of this feature.

**Comment by mathuo** [comment]
This has been release in version 1.9.0. Docs [here](https://dockview.dev/docs/next/components/dockview#maximized-groups)
