### ISSUE TITLE
TypeScript Documentation

### ISSUE THREAD

**Issue by muhamed87** [mathuo/dockview#383]
Hi,

I'm trying to find any documentation for the TypeScript to use this wonderful tool in an angular project, I tried to open the TSDoc link in the website but there is nothing like the normal documentation.

Could you update on this

**Comment by techbech** [comment]
Everything in the documentation is TypeScript :slightly_smiling_face:

**Comment by muhamed87** [comment]
So, do you think I can use this tool with Angular project, or only it is react dependent?

**Comment by mathuo** [comment]
dockview is split into two packages which are `dockview-core` and `dockview`.

- `dockview-core` contains the actual logic and implementions of almost the entire library as the library is mostly written in plain TypeScript for performance and framework compatiblity reasons.
- `dockview` is a lightweight React wrapper to allow seamless integration for those using React.

There are some limited examples on the docs for using `dockview-core` directly (for example those @techbech has referenced).

If you were using another framework such as Angular, Vue or anything else you could directly use the `dockview-core` package but it would may require some additional code given that `dockview-core` is written entire in TypeScript alone.

I do fully support the idea of having additional wrappers on dockview for other libraries and I would like to get around to providing wrappers specifically for other popular frameworks such as Angular.

I will keep an issue open for providing such wrappers but if anybody does end up using `dockview-core` with another library or framework I would be very interested to see their implementations.
