### ISSUE TITLE
Same panel in multiple tabs

### ISSUE THREAD

**Issue by danielefederico** [mathuo/dockview#384]
Hello there,
thanks for building this amazing project!

I was wondering if it could be possible to add support for having the same panel in multiple tabs. It would be great to have this as an option when registering the panels.
In my project, I need to have the same "panel type" in multiple tabs. It is essentially the same react component, but the content displayed would be different depending on each instance.
Currently I cannot do this as one panel can only be displayed in one tab.

I hope it makes sense.

Thanks!
Daniele

**Comment by mathuo** [comment]
Each panel renders it's content based on the `component` provided to it, the `component` can be used many times by any amount of panels but I feel like there may be more to your question than that so I'm not sure I entirely understand the question. 

I've created this brief sandbox example which creates 3 panels using the same `component` renderer for each. Would you be able to explain the question in the context of this example?

https://codesandbox.io/s/silent-snowflake-vgd8g7?file=/src/app.tsx

**Comment by danielefederico** [comment]
Thanks for replying! 

What I would like to do is to be able to instantiate the same panel multiple times. In your example, you register three panels with the same component, but then what if I need 50 panels using "component1". Currently, I would have to register each one.

An example could be how Adobe After Effects works. You can have multiple tabs (highlighted in blue), you usually have a master project and then you can then you can jump into groups (highlighted in red) too. You double click on them and then a the same track editor is shown with the group content. Groups contain tracks too, so it is essentially the same (React) component only showing a different "depth" of the project. You can have several tabs open (Panels in our case). 
![image](https://github.com/mathuo/dockview/assets/43070688/c6c14bf3-ee57-4781-a507-4421616f159d)

With your proposed solution, I would have to limit the panels to a predefined number (which is something I could do).
I was just wondering if it could become something more dynamic., something like:

`event.api.addPanel({
      id: "panel",
      component: "component1",
      params: {
        title: "Panel"
      },
      dynamic: True
    });`

Then each panel instance could have an "instance_id" property generated by dockview.

I hope it makes more sense now! I understand this is not a small change!

Thanks again!

**Comment by techbech** [comment]
I still find a bit hard to understand what you exactly trying to accomplish.

You can call `.addPanel(...)` as many times as you would like to at any time. The params provided can be used to determine what the component needs to render.

**Comment by danielefederico** [comment]
Thanks for replying, I think that solves my problem then.
Thanks for all the help and building this amazing project!
