### ISSUE TITLE
Gready rendering mode

### ISSUE THREAD

**Issue by mathuo** [mathuo/dockview#397]
The standard behaviour of dockview is to "de-render" any hidden panels (those panels that are not active). This is and will remain the default behaviour however there are some circumstances where it would be more benifical to leave all panels rendered but hidden (`display: none`) to preserve certain DOM specific state such as scroll position.

**Comment by raedle** [comment]
Come across this library recently and really digging it. Kudos!

I got a use case for greedy rendering of all tabs within a group where the tabs' content is semi-transparent (i.e., tabs are used as "overlays" for content in the left-most tab.

If I wanted to enable this today (even if hacky) where would be the best place to get started?

**Comment by mathuo** [comment]
Currently it would be enabled at a component level, not a indivual panel level through

```tsx
<DockviewReact ... renderMode='gready'/>
```

although the plan would be to make this a panel level parameter.

Little confused on your use case, any chance you could explain in some more detail so I can get a better idea of what you are trying to achieve? For example currently when hidden in gready mode with `display: none` it wouldn't be possible for the user to interactive with panel but it seems potentially you want multiple panels visible at once within one container?

**Comment by raedle** [comment]
For my use case, it would be ok if the setting is on the component level.

Use case:

I have a bunch of computer vision ML models that infer segmentation masks or bounding boxes for objects in an image. To compare the different checkpoints, I would like to have a flexible layout that would allow me to arrange model outputs side-by-side or layered on top of each other in z-index. The latter is to compare model results pixel-wise.

The `dockview` component already provides most of the UI and interaction that I want. For example, I can arrange outputs rendered in panels side-by-side where each panel contains the input image and segmentation masks or bounding boxes on top of an image (as SVG elements).

Now, for the z-index layering, it should render the input image in one tab, and then tabs on top in the same tab group should just render the segmentation masks or bounding boxes. Maybe one way to think about this is the layers view in Photoshop (see screenshot).

![image](https://github.com/mathuo/dockview/assets/489051/fc55f217-b109-42db-83c8-40596751a690)

So, for this to work, it needs to render contents of all tabs, with each tab having a transparent background, so it shows the contents of the tabs "underneath"

**Comment by techbech** [comment]
> So, for this to work, it needs to render contents of all tabs, with each tab having a transparent background, so it shows the contents of the tabs "underneath"

I really think that goes about outside of scope of dockview. I personally don't want to see dockview be a full blown UI dnd framework, but keep at just being a tab-docking-framework. What you describe can easily be implemented with something like https://github.com/atlassian/react-beautiful-dnd and you can still combine that with dockview

**Comment by osama095** [comment]
Hello @mathuo any updates on the release of the greedy mode? We love using the library and our use case requires a greedy mode :(

**Comment by mathuo** [comment]
The work for this PR is essentially done. I am planning to add additional unit tests before an offical release however I will aim to get out an experimental build in the next day or so for those interested in early usage.

**Comment by mathuo** [comment]
I've published the current state of this branch as an experimental build which can be installed through the following command.

`npm install dockview@0.0.0-experimental-a2a4e68-20231225`

> Variable names are subject to change however the core behaviours of what you see here are what is intended to be merged into master and released into an offical build soon.

You can specify a renderer for a specific panel through the `renderer` prop. When set at the panel level this information is persisted as a part of the serialized layout `toJSON()` which can be re-created through `fromJSON(...)`. 

```tsx
api.addPanel({
     id: 'my_panel_id',
     component: 'my_component',
     renderer: 'gready' // or 'destructive'
});
```

> If no `renderer` is provided the default will be used which can be specified at the component level described below. The default is `destructive` which is the current behaviour in existing versions of dockview.

If you want to change the default behaviour you can specify a `defaultRenderer` at the component level. This information is not persisted as a part of any serialized layout.

```tsx
<DockviewReact {...otherProps} defaultRenderer={'gready'}/>
```

**Comment by mathuo** [comment]
Refer to https://github.com/mathuo/dockview/issues/365 for beta builds and documentation of this feature.

**Comment by mathuo** [comment]
This has been release with version 1.9.0. Docs [here](https://dockview.dev/docs/components/dockview#panel-rendering)

I've opened another Issue for the "ovlerayed contents" idea [here](https://github.com/mathuo/dockview/issues/445)
