### ISSUE TITLE
How to keep group remain after last child has been removed?

### ISSUE THREAD

**Issue by KaivnD** [mathuo/dockview#402]
Hi, everyone! I'm making a simple web code editor, simply layout, like this.
![Lhdt4FiLVg](https://github.com/mathuo/dockview/assets/37983330/4614cef8-d6cb-4647-9e65-6528bcdd38e0)
On the left is a explorer side bar, and the right side is a document area, currently document area is a empty group, `watermarkComponent` shows up.

When explorer selected item changed, document area changed as well, and make this file actived.
![0OKB4Nr5Hh](https://github.com/mathuo/dockview/assets/37983330/ce162c32-275a-4665-b4a9-a44c29554b72)

So far so good, what a nice library, thanks for that. Here comes the problem, when I remove all child of document group, this group has been removed as well, but I don't want that.
![oZR9ymlcNt](https://github.com/mathuo/dockview/assets/37983330/0b2362de-fdfe-4d03-9090-13ca629361cb)

Any way to keep this group remainning? back to `watermarkComponent` show up states? like first image.

**Comment by KaivnD** [comment]
Maybe I found the option to control this behavior

https://github.com/mathuo/dockview/blob/ef70ea236d85c0d2cfcbc65b4f919da74240784f/packages/dockview-core/src/dockview/dockviewComponent.ts#L1026C5-L1050

Can we make this `removeEmptyGroup` via group api?

**Comment by KaivnD** [comment]
I have made a pr for this, is that ok? @mathuo

**Comment by techbech** [comment]
If you don't have plans to allow the files tab go outside the editor area, you could make a dockview in the editor and create something like this https://codesandbox.io/p/sandbox/dreamy-fast-ykr28h

![image](https://github.com/mathuo/dockview/assets/1520592/7d487a99-623d-4a9d-a910-d06e4e868c6f)
![image](https://github.com/mathuo/dockview/assets/1520592/b66b2033-c79d-440e-b586-95d6ab11c671)

**Comment by KaivnD** [comment]
@techbech wow, that's interesting! I'm so dumb. but this option maybe quite useful

**Comment by KaivnD** [comment]
maybe it's better in your way @techbech, forget about that #403
