### ISSUE TITLE
Sandbox Broken

### ISSUE THREAD

**Issue by sachnk** [mathuo/dockview#428]
**Describe the bug**
Sandbox example that demos dockview functionality isn't working. See error:

```
TypeError
props.containerApi.hasMaximizedGroup is not a function
RightControls
/src/app.tsx:128:27
  125 | }, [props.isGroupActive, props.activePanel]);
  126 | 
  127 | const [icon, setIcon] = React.useState<string>(
> 128 |     props.containerApi.hasMaximizedGroup()
      |                       ^
  129 |         ? 'collapse_content'
  130 |         : 'expand_content'
  131 | );
````

**To Reproduce**
Browse to the [linked sandbox example](https://codesandbox.io/p/sandbox/github/mathuo/dockview/tree/master/packages/docs/sandboxes/demo-dockview). 

**Expected behavior**
The sandbox example should compile and render correctly.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Browser: chrome
 - Version: 119.0.6045.199

**Additional context**

**Comment by mathuo** [comment]
Sorry, this is broken due to it contains uncoming changes that have yet to be released.

I've commented out these new features on the demo sandbox and it should work now
