### ISSUE TITLE
Content container does not scroll

### ISSUE THREAD

**Issue by NaNgets** [mathuo/dockview#446]
**Describe the bug**
The content container does not scroll if its contents is larger than the panel size.

**To Reproduce**
Create a new panel with a big size contents.

**Expected behavior**
The content container should allow scrolling.
The docs have an example in which the content has an element which it scrolls and not the content container. Is that by design? if so, why?

**Suggested fix**
Change `overflow: auto;` in content container class in dockviewGroupPanel.scss

**Comment by mathuo** [comment]
This is currently intentional to prevent scroll by default (forcing the user to create an inner container that is scrollable if they choose) within the container but I agree it would be better the otherway around now.

**Comment by NaNgets** [comment]
Hi, after reviewing the fix - I think it can be done better.

Your solution still makes the dock panel template in charge of the height and scroll from inside (i.e. encapsulate it in a div with height 100% and overflow auto).

I think you can make another option to the addPanel function which indicates whether we want auto scroll or not, and if so - add a new class which adds the overflow auto to the content-container element.

What do you think?

**Comment by NaNgets** [comment]
poke @mathuo
