### ISSUE TITLE
Feature request: Adding a gap around panels

### ISSUE THREAD

**Issue by synecdokey** [mathuo/dockview#447]
I'm trying to get a gap around the panels, and around them, but nothing I've tried seems to work, as the .groupview is `position:absolute`. Since width and height are managed by dockview, a pure CSS solution seems out of reach, even using margins on the element is impossible.

A small `gap` property on the dock view would be appreciated, as I don't think CSS can solve it in this case.

What I'd want ideally is something that can look like this, which seems impossible at the moment unless I missed something:
<img width="639" alt="Screenshot 2024-01-17 at 11 02 38 AM" src="https://github.com/mathuo/dockview/assets/58845835/ddb02a55-bc7b-40d6-9016-4d5f4f8b2a28">

**Comment by mathuo** [comment]
There is a theme that is shipped with `dockview` but it's more of an experiment than something that was really intended for use which is similar to what you are describing here.

I did battle with getting a gap to appear on this theme and you can see the CSS code [here](https://github.com/mathuo/dockview/blob/master/packages/dockview-core/src/theme.scss). I do wonder if this could be better achieved though through the library exposing some kind of CSS variable define the gap size, let me have a see what can be done.


Within the docs website you can switch to this theme as below:

![image](https://github.com/mathuo/dockview/assets/6710312/144bf78b-326f-4c7c-884f-249216c95cf3)

**Comment by mathuo** [comment]
Released in 1.10.0 https://dockview.dev/
