### ISSUE TITLE
Drop target selection transformation scales borders and outlines

### ISSUE THREAD

**Issue by obaida-adi** [mathuo/dockview#448]
Outlines and borders provided to drop-target-selection will scale with the transformation, resulting in an inconsistent outline.
In the cases where the drop-zone is the extreme top, bottom, left or right of the view, the border is scaled such that it essentially disappears.

Consequently, I've found that using `--dv-drag-over-border-color` doesn't work.

1. Add a dashed outline or a border to the drop-target-selection

Expected that outlines and borders do not scale with the drop-target-selection transformation. This could probably be fixed with a wrapper around drop-target-selection.

![image](https://github.com/mathuo/dockview/assets/29341751/08bc5165-7b69-4959-a2b1-2a64950585ce)
![image](https://github.com/mathuo/dockview/assets/29341751/af283a74-94c1-4dac-8c36-1a3c7e09ce03)

 - Browser: Chrome
 - Version: 120.0.6099.216 (Official Build) (x86_64)

**Comment by mathuo** [comment]
Thanks for the report, I'm not entirely sure on how to re-produce this. Would you be able to re-produce it using one of the sandboxes? 

Here's one that you may be able to use

https://codesandbox.io/s/github/mathuo/dockview/tree/master/packages/docs/sandboxes/simple-dockview

**Comment by obaida-adi** [comment]
Sure. Simply add the following snippet to `styles.css`:
```
.drop-target-selection {
  border: 10px dashed blue;
}
```
![image](https://github.com/mathuo/dockview/assets/29341751/1ce232c3-e400-45f7-b058-e299464245b5)

**Comment by mathuo** [comment]
> Sure. Simply add the following snippet to `styles.css`:
> 
> ```
> .drop-target-selection {
>   border: 10px dashed blue;
> }
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/29341751/298690104-1ce232c3-e400-45f7-b058-e299464245b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NjIzMTAsIm5iZiI6MTcwNTk2MjAxMCwicGF0aCI6Ii8yOTM0MTc1MS8yOTg2OTAxMDQtMWNlMjMyYzMtZTQwMC00NWY3LWIwNTgtZTI5OTQ2NDI0NWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDIyMjAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzM2IyZGNmMTQ0YjZlZTJkY2UzMjFjMGM4MGVkM2IxZmQyMjE5NWFjMDcxNGUyMWRiZDBhYjk4NmQ0OGFhOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nNcHSWuu3gz01YRDCuSw1RSvv54WzAzHWzzkid3jIHM)

I understand what you mean now - sorry didn't quite get it the first time. Since the scale transformation is applied to the same element you would want to add a border too the border is scaled too causing weird scaling issues for dashed borders, as an example - will look into that!


![image](https://github.com/mathuo/dockview/assets/6710312/d6c312ab-f136-4a8d-8d06-b2644256ab00)

**Comment by mathuo** [comment]
Released in 1.10.0 https://dockview.dev/
