### ISSUE TITLE
Examples don't work with Vite.

### ISSUE THREAD

**Issue by TylerAtCodeOfLife** [mathuo/dockview#456]
When I move the code over from the first codesandbox example into a new vite project I'm only left with a button to reset.

I've recreated the issue on the vite-react-ts stackblitz template here
https://stackblitz.com/edit/vitejs-vite-u9qzur

when i inspect the element i found that the issue is a css height set to 0px here:
    <div class="grid-view dv-dockview" style="height: 0px; width: 1847px;">

Thanks for reading

**Comment by mathuo** [comment]
Looks like you just needed to import `App.css` within `App.tsx` using `import ./App.css` - might be some differences with how codesandbox (which I believe is webpack) and StackBlitz (with Vite) work.

Forked example [here](https://stackblitz.com/edit/vitejs-vite-mrxzrk?file=src%2FApp.tsx)
