### ISSUE TITLE
Locked mode: prevent all mouse resizing

### ISSUE THREAD

**Issue by mathuo** [mathuo/dockview#460]
I guess there are two features here:
1. Disable mouse-interaction based resizing
    - I think this could be achieved entirely through CSS making it a fairly small change that is required.
2. Disable the dnd drop functionality 
    - This one is more involved but actually seems to be fairly similar to an existing issue [here](https://github.com/mathuo/dockview/issues/395) which I have been doing some work on which is to expose a function allowing control of whether dnd overlays are shown, in your case this function would just disable all overlays.

_Originally posted by @mathuo in https://github.com/mathuo/dockview/discussions/457#discussioncomment-8180480_

**Comment by mathuo** [comment]
Released in 1.10.0 https://dockview.dev/

**Comment by husayt** [comment]
thanks for this, Would be also good to have similar for gridview options, but as suggested I achieved that with css. So not a big deal.

**Comment by amirmamaghani** [comment]
Can you provide an example for disabling resizing? I can see that disableDnd is working but nor sure about resizing.

**Comment by SciManJD** [comment]
It will be really nice is somebody post an example about this issue. I want to disable the resizing only for specific panels. I thought that if I set equal values to minimumWidth, maximumWidth and minimumHeight, maximumHeight I will reach this effect, but this doesn't work.
I also forgot to tell that I'm trying to do this with a floating panel.
