### ISSUE TITLE
Is there any way to focus the panel content?

### ISSUE THREAD

**Issue by DanielGarciaGuillen** [mathuo/dockview#479]
Hello!

First of all, thanks for the lib!

I am trying to **focus** on the content of a Panel (we are opening the panel from a sidebar). 

When clicking on a sidebar item, the panel does not get focused.

I would appreciate it if you could provide some information about the focus provided by the [API](https://github.com/mathuo/dockview/blame/b901f4de0c36a8ed21eb62f38bfa807e1d816490/packages/dockview/src/dockview/reactContentPart.ts#L35) or another approach I should consider to be able to focus on the content of a panel when the panel is active.

[Codesandbox](https://codesandbox.io/p/sandbox/currying-waterfall-285hzv?file=%2Fsrc%2Fapp.tsx%3A221%2C64&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clruuedr400063b6i4xe0t0uo%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clruuedr400023b6iejpz0y3k%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clruuedr400033b6ic6mdiz0z%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clruuedr400053b6ixo0zi36r%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clruuedr400023b6iejpz0y3k%2522%253A%257B%2522id%2522%253A%2522clruuedr400023b6iejpz0y3k%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clruwfwwp00023b6i1hhz3svw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fapp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A221%252C%2522startColumn%2522%253A64%252C%2522endLineNumber%2522%253A221%252C%2522endColumn%2522%253A64%257D%255D%257D%255D%252C%2522activeTabId%2522%253A%2522clruwfwwp00023b6i1hhz3svw%2522%257D%252C%2522clruuedr400053b6ixo0zi36r%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clruuedr400043b6iy9jw2asi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clruuedr400053b6ixo0zi36r%2522%252C%2522activeTabId%2522%253A%2522clruuedr400043b6iy9jw2asi%2522%257D%252C%2522clruuedr400033b6ic6mdiz0z%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clruuedr400033b6ic6mdiz0z%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) 

To check what element is active dynamically:

> Open the Console.
> Click the Create live expression button (it looks like an eye icon).
> In the text box that appears, type document.activeElement.
> Now click/tab around the page and see the live expression update to reflect which element is currently focused.

Thanks!

**Comment by DanielGarciaGuillen** [comment]
@mathuo  thanks for your work!
Just a note, I have being using the `onDidActiveChange` event. I found an issue, when having a couple of panels in a group, when moving one panel to another group, the event on the listener gives you the wrong active panel.

Here is a [codesanbox](https://codesandbox.io/p/sandbox/sweet-johnson-pshccx?file=%2Fsrc%2Fapp.tsx%3A98%2C64), Panel 2 is active, if you move Panel 2 out of the group, the Panel 1 event listener says that the panel 1 is active for a bit before setting it to false.

**Comment by mathuo** [comment]
v1.10.0 has a few substancial changes around how events are fired and how things are made "active" and focused. 

Hopefully this demo is useful in understanding the events https://dockview.dev/demo/

Do let me know if things are still not covered as expected though.

**Comment by DanielGarciaGuillen** [comment]
@mathuo the updated fixed the issue regards moving the groups thanks!!!

But the focus method on panel (like mentioned on the first message here) still does not seems to be do what it says (focus the panel), is this intentional?
