### ISSUE TITLE
Popout iframe display

### ISSUE THREAD

**Issue by sachnk** [mathuo/dockview#486]
**Describe the bug**
When popping out a panel that has an `iframe`, the popped out window doesn't render the `iframe`. It also sometimes seems to leave behind a phantom `div` that has the contents of the `iframe`. The behavior seems a bit non-deterministic -- sometimes it seems to work.

**To Reproduce**
[Sandbox here](https://codesandbox.io/p/sandbox/dawn-https-wntx7p?file=%2Fsrc%2Fapp.tsx%3A12%2C21). This sandbox makes the following changes: a) Adds a new component called "framed" which simply renders an `iframe`, and b) Updates `panel_1` with `component: "framed"` and `renderer: "always"`.

1. Go to the [sandbox](https://codesandbox.io/p/sandbox/dawn-https-wntx7p?file=%2Fsrc%2Fapp.tsx%3A12%2C21).
2. Click on the pop-out window button that contains panel 1
3. See if panel 1 renders the `iframe` correctly

**Expected behavior**
Ideally, the `iframe` works as expected. Given that this is an `iframe`, I reckon it might be tricky.

**Screenshots**
![popout2](https://github.com/mathuo/dockview/assets/5503945/79ad3a7a-1dd7-4e71-a150-5ae99ecaad0e)

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 120.0.6099.234

**Additional context**
None

**Comment by mathuo** [comment]
Thanks for the report - this will fix be fixed as a part of the changes in https://github.com/mathuo/dockview/issues/469

**Comment by mathuo** [comment]
Released in 1.10.0 https://dockview.dev/
