### ISSUE TITLE
Subscription method for changes to panel params

### ISSUE THREAD

**Issue by benatross** [mathuo/dockview#489]
**Is your feature request related to a problem? Please describe.**
I have a custom Tab being passed to the defaultTabComponent prop. This custom tab relies on the Panel's params to determine what to render, which are passed into the Tab through the IDockviewPanelHeaderProps type. Whenever the params change (via panelApi.updateParameters(...)), the Tab component doesn't get re-rendered.

**Describe the solution you'd like**
A subscription function that I can use to listen for changes to the params object in a Panel, so that it can be used similarly to the other events.

<img width="526" alt="image" src="https://github.com/mathuo/dockview/assets/149530954/64d41922-b332-4bdf-976c-0de7913af727">

**Describe alternatives you've considered**
I currently have this working by wrapping the DockviewReact component in some react context, and passing my reactive state around this way. I would like to be able to pass my reactive state directly through the Panel's params.

**Additional context**
N/A

**Comment by mathuo** [comment]
I've made a quick sandbox [here](https://codesandbox.io/p/sandbox/fervent-resonance-28mr79?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqxyzjgq0006356j8evcmugp%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqxyzjgq0002356js9xus7ll%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqxyzjgq0003356jvv497ods%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqxyzjgq0005356j9gpr2tnd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqxyzjgq0002356js9xus7ll%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqxyzjgq0001356jnleia87t%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqxyzjgq0002356js9xus7ll%2522%252C%2522activeTabId%2522%253A%2522clqxyzjgq0001356jnleia87t%2522%257D%252C%2522clqxyzjgq0005356j9gpr2tnd%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqxyzjgq0004356jb21d1qkz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqxyzjgq0005356j9gpr2tnd%2522%252C%2522activeTabId%2522%253A%2522clqxyzjgq0004356jb21d1qkz%2522%257D%252C%2522clqxyzjgq0003356jvv497ods%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqxyzjgq0003356jvv497ods%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) which periodically called `updateParameters` and display the new value in both the content and a custom tab renderer. This seems to work for me, at least for the specific case I've created.

Would you be able to adjust this to your case where it no longer works so I can better understand the issue?

**Comment by benatross** [comment]
Ah, looks like the way we were using it was incorrect. Thanks for the example!
