### ISSUE TITLE
Dockview never auto-resizes to smaller height in flex layout

### ISSUE THREAD

**Issue by artaommahe** [mathuo/dockview#492]
**Describe the bug**

Dockview has an auto-resize feature, but it doesn't work if the new height should be smaller than the previous one inside flex layout.

**To Reproduce**

1. Go to https://stackblitz.com/edit/dockview-resize-issue?file=src%2FApp.tsx
2. Make the window's height smaller
3. See vertical scrollbar, `div.dv-dockview` height remains the same

**Expected behavior**

`.dv-dockview` should change its size to the smaller one

**Screenshots**

\-

**Desktop (please complete the following information):**
 - Browser: Chrome 
 - Version: Version 121.0.6167.139 (Official Build) (arm64)

**Additional context**

(btw docs for the auto-resizing feature are missed. There is this statement in the docs `Read about auto-resizing before using`, but nothing about auto-resizing anywhere)

**Comment by mathuo** [comment]
Thanks for repo. If you place `overflow: hidden` on the `.content` class then I believe your example auto-sizes the dock correctly?

**Comment by artaommahe** [comment]
@mathuo nope, only the scrollbar is removed, but the panel's height is still bigger than the new window height

**Comment by mcapodici** [comment]
Is this still an issue or been fixed since? The `overflow: hidden` fixed it for me, and also seems to have fixed it in your stackblitz link.

@artaommahe .
