### ISSUE TITLE
Save group restrictions as a part of layout object

### ISSUE THREAD

**Issue by MichailShcherbakov** [mathuo/dockview#493]
**Describe the bug**
The group constraints doesn't save and restore after layout persitance.

**To Reproduce**
[Link to Codesandbox](https://codesandbox.io/p/sandbox/friendly-water-hdc2k7?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls8xoilp00063j6gw0cx2svu%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls8xoilo00023j6gdys0skhg%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls8xoilp00033j6gmrsdbo8i%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls8xoilp00053j6g4gwjt8bz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls8xoilo00023j6gdys0skhg%2522%253A%257B%2522id%2522%253A%2522cls8xoilo00023j6gdys0skhg%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cls8xoilp00053j6g4gwjt8bz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls8xoilp00043j6g97n40wsf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cls8xoilp00053j6g4gwjt8bz%2522%252C%2522activeTabId%2522%253A%2522cls8xoilp00043j6g97n40wsf%2522%257D%252C%2522cls8xoilp00033j6gmrsdbo8i%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cls8xoilp00033j6gmrsdbo8i%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

https://github.com/mathuo/dockview/assets/50011226/e198688d-0b74-4929-931b-91eb578ffe7c

**Expected behavior**
The group constraints should be saved and restored after layout persistence.

**Comment by mathuo** [comment]
Group constraints currently come with quite a few limitations including the fact they are not persisted. It would need some careful though into how this might work if it was added.

I will leave this issue open and investigate at some point in the future.

**Comment by mathuo** [comment]
Tracking in https://github.com/mathuo/dockview/issues/640

**Comment by mathuo** [comment]
1.17.0 Releases changes related to initial, maximum and minimum sizes as well as a small change to prevent group resizing when moving groups.

See http://localhost:3000/docs/core/panels/add#minimum-and-maximum

See https://github.com/mathuo/dockview/issues/708 for continued work on group size preservation
