### ISSUE TITLE
API: onDidMaximizedGroupChange misspelled as onDidMaxmizedGroupChange

### ISSUE THREAD

**Issue by patrickemoore** [mathuo/dockview#495]
**Describe the bug**

The container api has onDidMaximizedGroupChange misspelt as onDidMaxmizedGroupChange (note the missing "i").

May seem minor, but just thought i'd raise as I didnt find it when i seached the api TS files for it with the correct spelling.

Amazing repo btw!

**To Reproduce**

component.api.d.ts line 459 on 1.9.2

**Comment by mathuo** [comment]
Thanks for the pointer - will get that fixed on the next release!

**Comment by mathuo** [comment]
Released in 1.10.0 https://dockview.dev/
