### ISSUE TITLE
Dockview does not support React.memo for components

### ISSUE THREAD

**Issue by patrickemoore** [mathuo/dockview#498]
**Describe the bug**.

Hi there!

I have several functional components in the Dockview "components" prop which are wrapped in React.memo for performance.

`const ExampleComponent = memo(function ExampleComponent() {
    return <>Example JSX</>;
});`

This throws the following error in the JS console, coming from dockview

![image](https://github.com/mathuo/dockview/assets/53632177/6c5cb117-8c54-4b68-b3eb-f82b73a2f731)

I was hoping to get support for these components, or maybe you can elaborate on why these are deliberately not supported if that's the case.

**To Reproduce**

1. Register any functional component wrapped in React.memo into Dockview
2. Render a pane with that component

**Expected behavior**

Not error

**Comment by mathuo** [comment]
Thanks for rasing the issue! 

There is no reason dockview should not support components wrapped in `React.memo` (or `React.ForwardRef` for that matter). I will get this changed, the current check is very old and not particularly clever. It simply checks if the input is `typeof function`.

**Comment by mathuo** [comment]
Released in 1.10.0 https://dockview.dev/
