### ISSUE TITLE
Improve group locking

### ISSUE THREAD

**Issue by patrickemoore** [mathuo/dockview#503]
**Is your feature request related to a problem? Please describe.**

Other group states all have a nice API (onDidMaximiseChange and onDidLocationChange). I would like to have a similar API for locked states

**Describe the solution you'd like**

OnDidLockedChange

**Describe alternatives you've considered**

Some listener to the locked state? not really sure.

**Additional context**

**Comment by mathuo** [comment]
Grouping into another issue [here](https://github.com/mathuo/dockview/issues/571)

**Comment by mathuo** [comment]
Grouping into another issue [here](https://github.com/mathuo/dockview/issues/571)
