### ISSUE TITLE
Disable multiple tabs being open side-by-side

### ISSUE THREAD

**Issue by ghost** [mathuo/dockview#506]
**Is your feature request related to a problem? Please describe.**
Multiple tabs open side by side cause issues with navigation. I have an id set in the path parameters and I want this id to reflect the open panel. It makes it hard to track which tab is open when multiple tabs are open side-by-side.

**Describe the solution you'd like**
A prop on dockview component that allows me to disable the side-by-side and drag and drop into multi window opened layout.

**Describe alternatives you've considered**
I could not create a solution with existing props available.

**Comment by mathuo** [comment]
Could you explain in more detail the problem pleasesince I'm not entirely sure what the problem you are describing is?

**Comment by mathuo** [comment]
Will re-open if issue has a response
