### ISSUE TITLE
Interested in porting dockview to Vuejs

### ISSUE THREAD

**Issue by afi-dev** [mathuo/dockview#538]
I'm really impressed with your project! I spent hours looking for a multi-window system, and coming across yours was just absolute bliss. However, I was a little disappointed to find that it is currently only compatible with React. I can't help wondering if there's any possibility of porting Vue.js in the future?

**Comment by mathuo** [comment]
@stefnotch @afi-dev  Moving discussion to [here](https://github.com/mathuo/dockview/issues/562). Vue.js wrapper is in active development.
