### ISSUE TITLE
Option to prevent closing tabs

### ISSUE THREAD

**Issue by supertorpe** [mathuo/dockview#563]
We have a use case where we need to create some tabs, drag&drop them around... but we don't want to allow the users to close tabs. I haven't seen in the docs an option to configure this behavior.

It would be useful to have a boolean option to allow/disallow closing tabs.

**Comment by techbech** [comment]
You can use custom tab components and, in that way, remove the close icon. As done here https://codesandbox.io/p/sandbox/polished-river-wsdfpz

It's briefly documented here https://dockview.dev/docs/core/panels/add#provide-a-custom-tab-renderer
