### ISSUE TITLE
Add group/data fields to onWillShowOverlay's event

### ISSUE THREAD

**Issue by artaommahe** [mathuo/dockview#564]
**Is your feature request related to a problem? Please describe.**

An `event` in `onWillShowOverlay` hook has very little information about what's going on. There are no data about tab/group that is dropping and tab/group we dropping to.

We have a pretty specific case - we need a group with several tabs (1-2) to be locked but having group's header visible (to switch between tabs and to show additional action in the tabs container). Current `group.lock` implementation still allows to move tabs inside locked group by dragging them over the header so we had to use `onWillDrop` hook to manually implement required logic. The only thing that remains and that we can't properly fix hacking around dropview's api - prevent drop zones to be shown over locked group's header and in the middle of the group (we still allow to drop to the side of the locked group so we need those drop zones). We wanted to use `onWillShowOverlay` for this, but `event` object there contains no information of what is dragged and where we want to drop to.

The described case is implemented here so you can clearly see the problem and partial solution

https://codesandbox.io/p/sandbox/dockview-prevent-dropzones-355pzd?file=%2Fsrc%2Fapp.tsx%3A23%2C32

**Describe the solution you'd like**

`event` object in `onWillShowOverlay` hook also provides `group` and `getData` fields/methods

**Describe alternatives you've considered**

Don't see any alternative for this with the current api. Having proper locked groups that doesn't allow to drop stuff via header would be better but that's an another story.

**Additional context**

~

**Comment by mathuo** [comment]
Released version `1.12.0` with the additional properties added to the `onWillShowOverlay` events and have noted the improved group options in general in another issues [here](https://github.com/mathuo/dockview/issues/571)
