### ISSUE TITLE
Expose panel component ID via the PanelApi

### ISSUE THREAD

**Issue by qcz** [mathuo/dockview#569]
When loading panels from JSONs it would be nice to known the ID of the component belonging to the loaded panels for bookkeeping reasons.

PanelApiImpl already has this info (I can access it using `(panel as any).api.component`), it is just not part of the public PanelApi interface.

It would be nice if its officially available in PanelApi.

**Comment by mathuo** [comment]
Fixed and published as version `1.12.0`

**Comment by qcz** [comment]
Thank you!
