### ISSUE TITLE
Opening a new tab without activating it

### ISSUE THREAD

**Issue by bjassael** [mathuo/dockview#572]
**Is your feature request related to a problem? Please describe.**
A common behavior in browsers is opening tabs without making them active (example : "cmd/control + click" in a new link)

**Describe the solution you'd like**
Could be possible to pass a variable to "addPanel" for choosing if a new panel is active or not.

**Comment by mathuo** [comment]
Makes sense - will look at getting this added

**Comment by bjassael** [comment]
Thank you!

**Comment by bjassael** [comment]
@mathuo do you have an estimated of when could this be merged? would be super good for us to have it 👍🏾.

**Comment by mathuo** [comment]
I'll try get it out this weekend. Sorry for the delay - in the process of also re-factoring some internals to support multiple frameworks which makes releasing a little tricker as I need to also validate those changes.

**Comment by mathuo** [comment]
Releast in 1.13.0 https://dockview.dev/docs/core/panels/add/#opening-a-basic-panel
