### ISSUE TITLE
Need an easy to to know if a panel/group is floating

### ISSUE THREAD

**Issue by ztolley** [mathuo/dockview#583]
I am building a layout in which I want users to be able to click on a control to make panel float and if floating provide an alternative button to dock the panel or hide the float button.

As it stands its easy to make a panel float with `containerApi.addFloatingGroup(activePanel)` but there is no easy generic way to know if the panel is part of a floating group or not while constructing the function for rightHeaderActionsComponent.

**Comment by mathuo** [comment]
Both the panel and group `api` object expose a `location` property as an object:

```ts
type DockviewGroupLocation = {
    type: 'grid';
} | {
    type: 'floating';
} | {
    type: 'popout';
    getWindow: () => Window;
};
```

For example `api.location.type` for floating groups should be equals to `floating`.

I realize now though this may not be well documented, let me know if this is what you are looking for though?
