### ISSUE TITLE
onDidLayoutChange callback catches panels init

### ISSUE THREAD

**Issue by artaommahe** [mathuo/dockview#597]
**Describe the bug**

`onDidLayoutChange` callback is triggered after panels were initialised inside `onReady` callback despite callback being registered after adding panels.

**To Reproduce**

1. Go to https://stackblitz.com/edit/vitejs-vite-6lyqey?file=src%2FApp.tsx
2. See triggered `onDidLayoutChange` in the console

**Expected behavior**

`onDidLayoutChange` should be triggered only on following layout changes

**Screenshots**

\-

**Desktop (please complete the following information):**
 - Browser Chrome on Mac
 - Version 124.0.6367.119

**Additional context**

As i see in debugger layout changes are fired through Emitter that triggers callbacks inside a setTimeout, looks like that's the reason why a onDidLayoutChange callback registered after adding panels catches those changes as a layout change.  

We're implementing saving the layout to the database and for now have to bypass this behaviour with wrapping onDidLayoutChange listener with a setTimeout that doesn't look stable and relies on Emitter's behaviour.

**Comment by mathuo** [comment]
Thanks for the details description and analysis of the source code.

I have now made the required changes for this to work correctly and it is released in 1.13.1
