### ISSUE TITLE
dockview.dev won't load

### ISSUE THREAD

**Issue by willcrichton** [mathuo/dockview#609]
When I visit in Chrome, I get:

```
This site can’t provide a secure connection

dockview.dev sent an invalid response.

ERR_SSL_PROTOCOL_ERROR
```

**Comment by TheSisb** [comment]
Works for me

**Comment by mathuo** [comment]
I did check this quickly and seems to work for me too. 

The site will only run on `https` but your browser should auto-direct if you attempt to access `http://dockview.dev`. Perhaps a firewall issue if you are still seeing it?

**Comment by willcrichton** [comment]
I'm no longer encountering this issue either. Idk if it was on my end or a transient configuration.
