### ISSUE TITLE
Gap between panels leads to some panels' size overflow

### ISSUE THREAD

**Issue by artaommahe** [mathuo/dockview#613]
**Describe the bug**
Having a layout with nested branches and gaps between panels (`--dv-group-gap-size: 0.5rem;`) leads to some panels' overflowing their expected boundaries (panels 4 and 5 in the screenshot)

![image](https://github.com/mathuo/dockview/assets/1944061/57ac18ab-4108-45e8-a9c4-cc7dd1bc9117)

**To Reproduce**

1. Go to https://stackblitz.com/edit/vitejs-vite-wsic2s?file=src%2FApp.tsx,src%2Findex.css
2. See that panels' 4 and 5 are bigger than expected and overflow over the gap between panels

![image](https://github.com/mathuo/dockview/assets/1944061/ea80e52d-876c-4da4-a6f8-8d77bcaf2fd5)

**Expected behavior**

Nested panels respect gaps in their sizing calculation

**Screenshots**
^

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 124.0.6367.208

**Additional context**
\-

**Comment by mathuo** [comment]
Release in `1.14.1`

**Comment by artaommahe** [comment]
@mathuo the fix breaks group's custom styling (like border radius) 😅 you can check this at the demo page with replit theme


after update
![image](https://github.com/mathuo/dockview/assets/1944061/3a6a42c4-4330-441f-b5fb-862e2afb506f)


before (i just disabled gap's border style for one case, border radius is back)
![image](https://github.com/mathuo/dockview/assets/1944061/70e72131-6d32-43e0-8aa5-219864b1d0ea)

**Comment by mathuo** [comment]
> @mathuo the fix breaks group's custom styling (like border radius) 😅
> 
> you can check this at the demo page with the replit theme (i also made the gap bigger to showcase the issue)
> 
> after update ![image](https://private-user-images.githubusercontent.com/1944061/334731957-3a6a42c4-4330-441f-b5fb-862e2afb506f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMTAxMzMsIm5iZiI6MTcxNzAwOTgzMywicGF0aCI6Ii8xOTQ0MDYxLzMzNDczMTk1Ny0zYTZhNDJjNC00MzMwLTQ0MWYtYjVmYi04NjJlMmFmYjUwNmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjlUMTkxMDMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2ZlN2Y2MGVhMjZjNDNhMTE0NTg5ZjI3MzcyY2JkM2FlYjllOGNiM2M3Yzg5MzliNzk4ZmY4ODVmZTBiZTJjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DV7olAObEwRPEiOOz3-_LE9HSOEB8RJk_NNvOD55xMY)
> 
> before (with border gap back to `.view`, border radius and color are back) ![image](https://private-user-images.githubusercontent.com/1944061/334779323-b8182ea6-4ded-4bf4-a44f-6c3b6375a3b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMTAxMzMsIm5iZiI6MTcxNzAwOTgzMywicGF0aCI6Ii8xOTQ0MDYxLzMzNDc3OTMyMy1iODE4MmVhNi00ZGVkLTRiZjQtYTQ0Zi02YzNiNjM3NWEzYjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjlUMTkxMDMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjZkZTZhMzA3ZTg5MzM5ZjUwOGQ4ZTg4N2Y2OWQ3YTYyYzhkMTAwYTk1YmZiMjlkMTA3ODc2NmM2NzlmMTBhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jnz76LtXyiaOvK4hOHnizRrk0wgeLDT88iMVkowCPu4)

damn, I guess this needs a bit more though. Let me have a think

**Comment by mathuo** [comment]
`1.15.0` now uses a prop `gap` defined in pixels . The CSS property `--group-gap-size` is no longer used.

Let me know if this does the trick.

**Comment by artaommahe** [comment]
@mathuo looks like passing `gap={6}` to the `DockviewReact` component doesn't work - https://stackblitz.com/edit/vitejs-vite-9f1xvv?file=src%2FApp.tsx,package.json

**Comment by mathuo** [comment]
Looks like I missed testing this directly through React and only tested through the `api` object - should all be working as expected in `1.15.1`.

**Comment by artaommahe** [comment]
@mathuo it works, thx a lot )
