### ISSUE TITLE
dockview-vue error Cannot read properties of null (reading 'appContext')

### ISSUE THREAD

**Issue by rasmushallstrom** [mathuo/dockview#624]
**Describe the bug**
I'am using dockview-vue.
In many instances i get this error
`Cannot read properties of null (reading 'appContext')`

**To Reproduce**
A simple way to reproduce this is just go to the documentation.
In many of the live examples for vue on the dockview site don't work like the react live examples. For instance adding a floating group/empty group

1. https://dockview.dev/docs/core/watermark
2. Click on 'vue' examples
3. Scroll down to 'live examples'
4. Press add empty group

1. https://dockview.dev/docs/core/groups/floatingGroups
2. Click on 'vue' examples
3. Scroll down to 'live examples'
4. Press add floating group

The error occurs when getCurrentInstance() is called and returns null, it is used as parent is this function in dockview-vue.

```javascript
function findComponent(parent, name) {
  var _a, _b;
  let instance = parent;
  let component = null;
  while (!component && instance) {
    component = (_a = instance.components) == null ? void 0 : _a[name];
    instance = instance.parent;
  }
  if (!component) {
   // Error coming from here, parent is null and throws
    component = (_b = parent.appContext.components) == null ? void 0 : _b[name];
  }
  if (!component) {
    throw new Error(`Failed to find Vue Component '${name}'`);
  }
  return component;
}
```

**Comment by mathuo** [comment]
Fixed in `1.14.2`
