### ISSUE TITLE
After all the groups in the branch are hidden, an error is reported when calling fromJSON()

### ISSUE THREAD

**Issue by zhaijunlei955** [mathuo/dockview#630]
1、![c39ce73bf0b7b1915b5bae04e714d5d0](https://github.com/mathuo/dockview/assets/49547008/5dd93c8f-1bf6-47c3-bbd6-fdea99cbfb4b)

2、
![19a676e50dfcc9edca05252e09c17175](https://github.com/mathuo/dockview/assets/49547008/4988024d-9ea5-4e29-bc6e-ffdd85a9f6ac)

3、
![aa2c217b950919f63f6ae4e1a2b9e375](https://github.com/mathuo/dockview/assets/49547008/a635e3f6-b283-485f-81ab-40f857eb299b)

**Comment by zhaijunlei955** [comment]
**This error report will occur when the group is hidden and the length of the group's panels is 0**

**Comment by zhaijunlei955** [comment]
Or the number of panels of the group is not 0. After hiding all groups of the branch (the number of groups>=2), calling fromJSON again, and then calling setVisible to show the group is invalid

**Comment by mathuo** [comment]
This should be fixed in the latest version `1.15.1`.
