### ISSUE TITLE
Initial width and height of a docker panel

### ISSUE THREAD

**Issue by shashi-drishya** [mathuo/dockview#632]
Hi @mathuo,

I am wondering if there is currently a feature that allows specifying the initial size of a panel, where both the height and width can be defined during setup.

**Comment by mathuo** [comment]
I believe this is probably something similar to https://github.com/mathuo/dockview/issues/590

i.e. when it is possible (since it's not always possible to use an exact height and width) use a user-defined preferred height and width

Let me know if that makes sense?

**Comment by mathuo** [comment]
Tracking in https://github.com/mathuo/dockview/issues/640

**Comment by mathuo** [comment]
Released in 1.17.0 

See http://localhost:3000/docs/core/panels/add#initial-size

See https://github.com/mathuo/dockview/issues/708 for continued work on group size preservation

**Comment by shashi-drishya** [comment]
Thank you, @mathuo, for implementing this feature!
