### ISSUE TITLE
How to set minimum and maximum panel sizes in DockView?

### ISSUE THREAD

**Issue by gkhnoztrk** [mathuo/dockview#639]
Hi,

I'm currently working on a project using the DockView library, and I'm trying to implement size constraints for my panels. Specifically, I want to set minimum and maximum sizes for each panel to ensure they don't become too small or too large when users resize them.

I've looked through the documentation but couldn't find a clear way to achieve this. Is there a built-in method or property in DockView to set minimum and maximum sizes for panels?

My use case requires that panels:
- Don't shrink below a certain width and height
- Don't expand beyond a certain width and height

Could you please provide guidance on the proper way to set these size constraints for panels in DockView? If this feature isn't currently available, are there any workarounds or plans to implement it in the future?

Thank you for your time and assistance.

**Comment by mathuo** [comment]
Tracking in https://github.com/mathuo/dockview/issues/640

**Comment by mathuo** [comment]
Released in 1.17.0

See http://localhost:3000/docs/core/panels/add#minimum-and-maximum

See https://github.com/mathuo/dockview/issues/708 for continued work on group size preservation
