### ISSUE TITLE
Dockview 1.17.0 Iteration Plan [RELEASED]

### ISSUE THREAD

**Issue by mathuo** [mathuo/dockview#641]
Release Date: TBA

Issues
- https://github.com/mathuo/dockview/issues/640
- https://github.com/mathuo/dockview/issues/639
- https://github.com/mathuo/dockview/issues/632
- https://github.com/mathuo/dockview/issues/589
- https://github.com/mathuo/dockview/issues/493

**Comment by qcz** [comment]
If not for 1.16, it would be useful in the future if groups created ad hoc by moving panels around would retain their size when moving around (eg. moving an ad-hoc group from left to the right in the same row or from top to bottom in the same column should not result in the resize of the width/height of that group.

**Comment by vincent-lecrubier-skydio** [comment]
@mathuo this release sounds awesome, do you have an estimate on when you'd release it? The ability to set min/default/max sizes for items is a must-have on our side, I'm very curious if there anything we can do to help

**Comment by leobudima** [comment]
> @mathuo this release sounds awesome, do you have an estimate on when you'd release it? The ability to set min/default/max sizes for items is a must-have on our side, I'm very curious if there anything we can do to help

Same here! I'm so ecstatic about all the features of the library and how it would transform my project - the only thing that I need to wait on is the dimensions config. Good luck with the functionality, @mathuo , and thank you so much for the awesome work!

**Comment by mathuo** [comment]
1.17.0 releases changes related to initial, maximum and minimum sizes as well as a small change to prevent group resizing when moving groups.

See http://localhost:3000/docs/core/panels/add#minimum-and-maximum

See https://github.com/mathuo/dockview/issues/708 for continued work on group size preservation
