### ISSUE TITLE
renderer always causes floating group z-index bug

### ISSUE THREAD

**Issue by chhsgithub** [mathuo/dockview#656]
same as this: https://dockview.dev/docs/advanced/iframe
which not noly iframe, but also normal dom element act not correctly
panel 1 is active, but covered by panel 2
<img width="889" alt="image" src="https://github.com/user-attachments/assets/a14aaab5-13e1-4cbf-be85-0fd9683b90a0">

**Comment by chhsgithub** [comment]
It seems that the z-index of element in floating panel is not following with panel container. 
<img width="899" alt="image" src="https://github.com/user-attachments/assets/f2080378-4e18-46db-b948-6681ca98e4e1">
<img width="1830" alt="image" src="https://github.com/user-attachments/assets/ae394045-e6d9-48bd-8f4d-4946e891cee2">
<img width="1798" alt="image" src="https://github.com/user-attachments/assets/49ae9cf9-0eb3-436d-8dd6-9a6af4be5e3d">

**Comment by mathuo** [comment]
Fixed in `1.16.0`
