### ISSUE TITLE
floating group setVisible will crash

### ISSUE THREAD

**Issue by chhsgithub** [mathuo/dockview#665]
<img width="937" alt="image" src="https://github.com/user-attachments/assets/4f0f4bef-2f74-46b8-bf7c-8e3079491ece">
<img width="341" alt="image" src="https://github.com/user-attachments/assets/db7f1fe0-9b20-4663-a33e-59a3552d2b40">

**Comment by chhsgithub** [comment]
<img width="1714" alt="image" src="https://github.com/user-attachments/assets/ae0ce26c-6989-4a57-a9f6-2466005b31b1">

**Comment by mathuo** [comment]
Released in 2.1.0
