### ISSUE TITLE
Floating panel documentation example not working

### ISSUE THREAD

**Issue by pchevilley** [mathuo/dockview#677]
The example for adding a floating panel in the [documentation](https://dockview.dev/docs/core/panels/add#floating) uses the wrong properties for the position. Instead of "left" and "top" it should be "x" and "y".

```
api.addPanel({
    id: 'panel_2',
    component: 'default',
    floating: { left: 10, top: 10, width: 300, height: 300 },
});
```
=>

```
api.addPanel({
    id: 'panel_2',
    component: 'default',
    floating: { x: 10, y: 10, width: 300, height: 300 },
});
```

**Comment by mathuo** [comment]
`x`, `y` is intended to be deprecated in favour of `top`, `left`, `bottom`, `right` which is already available in current versions through the `floating.position` property. I will update the docs to reflect this.

```tsx
api.addPanel({
  id: 'panel_2',
  component: 'default',
  floating: {
      position: { left: 10, top: 10 },
      width: 300,
      height: 300
  }
});
```
