### ISSUE TITLE
Resize handlers position is wrong for more than 2 panels in one branch

### ISSUE THREAD

**Issue by artaommahe** [mathuo/dockview#681]
**Describe the bug**
Having a gap between groups and visible resize handlers (replit theme e.g.), the position of these handlers is wrong if there is more than 2 panels in one direction

**To Reproduce**

1. Go to https://dockview.dev/demo/?theme=dockview-theme-replit
2. Set the gap to 20px
3. Move panels so there is more than 2 in one direction (within the same branch)
4. See that resize handlers are off

**Expected behavior**
Handlers position is correct for any amount of panels in one branch

**Screenshots**
8 panels
<img width="1258" alt="image" src="https://github.com/user-attachments/assets/428f2933-dd0c-4f25-a817-6a0dca2283ad">

3 panels
<img width="947" alt="image" src="https://github.com/user-attachments/assets/c96a70a8-6894-4a94-a5f1-493979db7bf3">

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: Version 127.0.6533.89 (Official Build) (arm64)

**Additional context**

**Comment by mathuo** [comment]
Seems to be issues with the position of the first and last resize handle containers when gap > 0. Additionally there are some issues with gaps when some panels are hidden using `setVisible(false)` which @RayJason has raised partial PR fix. 

I will combine both issues into a fix for the branch assoicated with this issue.

**Comment by mathuo** [comment]
Fixed in `1.16.0`
