### ISSUE TITLE
Multiple classes on DockviewReact element doesn't work in 1.16.0

### ISSUE THREAD

**Issue by artaommahe** [mathuo/dockview#684]
**Describe the bug**
Having multiple css classes on DockviewReact component ends with an exception and dockview doesn't work.

```
Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('dockview-theme-abyss test') contains HTML space characters, which are not valid in tokens.
    at new BaseGrid 
    at new DockviewComponent
    at createDockview
```

**To Reproduce**

1. Go to https://stackblitz.com/edit/vitejs-vite-hrcja5?file=src%2FApp.tsx
2. See an error in devtools

**Expected behavior**
Any amount of classes on DockviewReact work. 

**Screenshots**
-

**Desktop (please complete the following information):**
 - Browser chrome
 - Versio 127.0.6533.100 (Official Build) (arm64)

**Additional context**
Worked fine before 1.16.0

**Comment by mathuo** [comment]
Fixed in 1.16.1. Error was due to some internal refactoring to expose a vanilla javascript version of dockview which the react version is using internally.
