### ISSUE TITLE
Keep the panel content

### ISSUE THREAD

**Issue by ArgoZhang** [mathuo/dockview#691]
**Is your feature request related to a problem? Please describe.**
If there are multiple Panels in a Group, when I switch their visibility, DockView always removes the invisible DOM, which is very inconvenient for me.

**Describe the solution you'd like**
I would prefer to only set the display style when switching Panels, which can save me a lot of logic.

panel1 visible
```
<div class="content-container" tabindex="-1">
    <div class="content">Panel1</div>
    <div class="content d-none">Panel2</div>
</div>

```

toggle panel2 visible
```
<div class="content-container" tabindex="-1">
    <div class="content d-none">Panel1</div>
    <div class="content">Panel2</div>
</div>
```

**Comment by vincent-lecrubier-skydio** [comment]
Did you try `renderer: 'always'` (Documented here: https://dockview.dev/docs/core/panels/rendering ) ? Feels like this is what you might want.

**Comment by ArgoZhang** [comment]
@vincent-lecrubier-skydio thank you for the quick reply. I will check it and reply later. that sound good.

**Comment by ArgoZhang** [comment]
@vincent-lecrubier-skydio thank you very much. it's work now
