### ISSUE TITLE
When loading stored layout having popout grooups, dockview doesn't respect the popoutUrl passed instead it defaults it to popout.html

### ISSUE THREAD

**Issue by JanakiramMaddanala** [mathuo/dockview#705]
**Describe the bug**
When loading stored layout having popout groups, dockview doesn't respect the popoutUrl passed instead it defaults it to popout.html

**To Reproduce**
1. Popout a group
2. Save the layout to redux or local storage
3. Reload the page and load the saved layout
4. Popout windows use popout.html instead of the passed popoutUrl of DockViewOptions

 <DockviewReact
        components={components}
        onReady={onReady}
        onDidDrop={onDidDrop}
        defaultTabComponent={CustomTabComponent}
        popoutUrl={'popout.html?themeClass=dark-theme'}
      />

**Expected behavior**
Expecting the popout windows to have the supplied popoutUrl like `popout.html?themeClass=dark-theme` even during the initial load the dockview using api.fromJSON()

**Screenshots**
**Initial Load of Saved Layout using api.fromJSON()**
It doesn't have the themeClass query parameter in the url
![image](https://github.com/user-attachments/assets/a0529e87-2c6f-4dab-91d5-c52e53f8af0a)

**When opening popout of group by clicking on Icon**
Here it is respecting the url passed but not during inital load of dockview using saved layout
e.containerApi.addPopoutGroup(e.api.group, {
      popoutUrl: 'popout.html?themeClass=dark-theme',
      onDidOpen(_event) {},
      onWillClose(_event) {},
    });
    
![image](https://github.com/user-attachments/assets/1f2a5e72-b2af-4487-a941-3e9a41c2581b)

**Desktop (please complete the following information):**
 - Browser [Chrome]
 - Version [128.0.6613.114]

**Comment by mathuo** [comment]
Released in 2.1.0. Option will be persisted if provided as a panel option
