### ISSUE TITLE
Reloading of popout window is displaying blank page

### ISSUE THREAD

**Issue by JanakiramMaddanala** [mathuo/dockview#710]
**Describe the bug**
Reloading of popout window is displaying blank page

**To Reproduce**
1. Popout a panel or group
2. Right Click and Reload in the popout window
3. Page displays blank

**Expected behavior**
Expecting to see the same content on reload as well

**Desktop (please complete the following information):**
 - Chrome
 - Version 128.0.6613.120 (Official Build) (32-bit)

**Comment by mathuo** [comment]
Released in `2.0.0`. See https://github.com/mathuo/dockview/releases/tag/v2.0.0
