### ISSUE TITLE
Packages don't follow SemVer

### ISSUE THREAD

**Issue by trombipeti** [mathuo/dockview#711]
**Describe the bug**
I have "dockview": "^1.10.1" in my package.json, did an npm update, locked version got bumped from 1.10.1 to 1.17.1.
Since this is a minor version update, I would've expected backwards compatibility. But they are not, even the release notes talk about many breaking changes.

A specific error I got was that the `PanelCollection<T>` type doesn't exist anymore.

I have updated my code without a big hassle, but now I am afraid that more things have changed under the hood which are incompatible. I don't really want to / have the time to manually test everything now.

**Expected behavior**
Package follows SemVer, minor version updates are backwards compatible
...OR it is stated explicitly that the package does NOT follow SemVer, in which case I would change my package.json to only update the patch versions.

**Additional context**
I use a typescript based react project, originally created via create-react-app.

**Comment by mathuo** [comment]
Apologies - before dockview `1.18.0`-ish the library interfaces had been changing frequently as the library was standardized.

Now on version `3.0.0` dockview is following SemVer where breaking changes will only be released on major versions.
