### ISSUE TITLE
CSS variable --dv-background-color is always black which breaks theming of Auxilliary Components

### ISSUE THREAD

**Issue by alhimik45** [mathuo/dockview#716]
**Describe the bug**
In all themes `--dv-background-color` seems to be defined as `black` which slightly break coloring of dark themes and completely ruins light theme. Looks like this variable is used only in aux components, so Dockview is ok, but Splitview, Gridview and Paneview are broken.

**To Reproduce**
[Codesandbox](https://codesandbox.io/p/sandbox/competent-carson-tglllr) - this is Splitview example with `dockview-theme-light` set - it is still black.

**Expected behavior**
Splitview, Gridview and Paneview with light theme have some light backgroung

**Desktop:**
 - Browser Firefox
 - Version 129.0.2

**Comment by mathuo** [comment]
Thanks for the report, it seems that it will make the most sense to remove this property allowing the user to explicitly specific background color.

As you mentioned this property is only used on the split views, in the primary docking component this property is not used.

**Comment by mathuo** [comment]
Released in `2.0.0`. See https://github.com/mathuo/dockview/releases/tag/v2.0.0
