### ISSUE TITLE
setConstraints no longer works

### ISSUE THREAD

**Issue by borglin** [mathuo/dockview#717]
**Describe the bug**
Using `setConstraints` no longer has any effect. I can still resize a group how I want. The sandbox included in the docs shows this behaviour. If I fork the sandbox and use version 1.16.0 the constraints are working.

https://dockview.dev/docs/core/groups/constraints

**To Reproduce**
Using the sandbox from the docs, https://codesandbox.io/p/sandbox/github/mathuo/dockview/tree/gh-pages/templates/dockview/constraints/react

1. Click set on any panel
2. Resize to more than the maxWidth
3. The constraints display is not shown in the panel

Using the same sandbox but with v1.16.0 https://codesandbox.io/p/sandbox/flamboyant-moon-vzxntg it works

**Expected behavior**
When I use `setConstraints` the constraints are set and they prevent the resizing beyond the min/max size

**Comment by mathuo** [comment]
Released in `2.0.0`. See https://github.com/mathuo/dockview/releases/tag/v2.0.0
