### ISSUE TITLE
Allow customization of the DEFAULT_OVERLAY_Z_INDEX value

### ISSUE THREAD

**Issue by jdk2pq** [mathuo/dockview#720]
**Is your feature request related to a problem? Please describe.**
I want to be able to customize the `DEFAULT_OVERLAY_Z_INDEX` value to set it higher than 999. This will help ensure that floating Dockview groups and panels will always remain on top of other elements in my app, where some elements necessitate using `z-index: 1000`, but I still want the floating Dockview groups/panels to have a higher `z-index` than those elements.

**Describe the solution you'd like**
Add a function to set `DEFAULT_OVERLAY_Z_INDEX` or add it as a custom option in Dockview.

**Describe alternatives you've considered**
Adding my own CSS to target floating Dockview panels/groups. This seems less ideal because the `z-index` won't increment with each new panel/group, like it does when setting the `z-index` with `DEFAULT_OVERLAY_Z_INDEX`, and it will just be static.

Also, another alternative is patching this library to update the value from 999 to 1000. That's what I'm currently doing, but maintaining patches for libraries seems potentially flakey to me, so I'd ideally like to have support to change this value in the library.

**Additional context**

**Comment by mathuo** [comment]
@amirmamaghani I made a small change to rename the variable to `--dv-overlay-z-index` and use that variable in a couple more places. Everything is relative to this `--dv-overlay-z-index` value.

Ive deployed an experimental build from master with though changing if you did want to try it out, otherwise I'll aim to release an offical build in the coming days.

`0.0.0-experimental-8015860-20241009`

**Comment by amirmamaghani** [comment]
Thank you @mathuo , tested and works flawlessly. Thank you and looking forward to have it in official release.

**Comment by mathuo** [comment]
Published as `1.17.2`

**Comment by jdk2pq** [comment]
Thank you for the quick work on this @amirmamaghani and @mathuo! Really appreciate it!
