### ISSUE TITLE
`__dockview_internal_drag_event__` appearing in editor text after drag/drop of panel.

### ISSUE THREAD

**Issue by brochington** [mathuo/dockview#726]
Occasionally, when I drag a panel that contains a text editor (tested on both Monaco and Codemirror), a `__dockview_internal_drag_event__` is injected into the text that the editor is viewing. 

[dockview_bug_1.webm](https://github.com/user-attachments/assets/79b2c09e-3955-47d3-b929-cd089b06fd7b)

**Comment by mathuo** [comment]
Released in `2.0.0`. See https://github.com/mathuo/dockview/releases/tag/v2.0.0
