### ISSUE TITLE
fromJSON error while the json include popoutGroups

### ISSUE THREAD

**Issue by chhsgithub** [mathuo/dockview#747]
**Describe the bug**
api.fromJSON error while the json include popoutGroups

**To Reproduce**
with my own code when the json layout includes popoutGroups, it will cause an error "Error: Invalid grid element"
<img width="750" alt="image" src="https://github.com/user-attachments/assets/0f659fa2-3b8d-470e-99ea-fd00cb1d5350">

with https://dockview.dev/demo/, by using save and then load/refresh will cause empty dock
1. action load
popout->layout changed->load->dock empty
https://github.com/user-attachments/assets/a3abe296-d534-43d9-8790-1fddbcaea1a9

2. action refresh
popout->layout changed->refresh browser tab->dock empty
https://github.com/user-attachments/assets/f7cd3cc9-a87f-4c2e-8556-3af8e9cea7e1

**Comment by mathuo** [comment]
Released in `2.0.0`. See https://github.com/mathuo/dockview/releases/tag/v2.0.0
