### ISSUE TITLE
Add panel in a specific index within a group without making it active

### ISSUE THREAD

**Issue by bjassael** [mathuo/dockview#750]
Again @mathuo thank you for the great work. 

When adding a new panel to a group it gets added after the last panel in the group (either active or inactive).

We would like to be able to add it in any index within a group without making it active. As now, it is only possible to add it and right after move it (using moveTo) to the index desired. But moveTo sets the panel active, and we would like it to be inactive.
The idea of this is to mimic common browser behavior, where new tabs are added right after the active tab, instead of at the end. 

A Possible solution for this would be to add a flag to "moveTo" for moving a panel without making it active. Another option is to add an index parameter in the "Position" parameter when adding a new panel, but maybe this is more complicated.

**Comment by mathuo** [comment]
Nice suggestion!

will add `index` to both `api.addPanel` within the `position` argument and will add `index` to the `moveTo` methods on both the panel and group api too

**Comment by mathuo** [comment]
Released in `2.0.0`. See https://github.com/mathuo/dockview/releases/tag/v2.0.0

**Comment by bjassael** [comment]
Great! Thank you @mathuo! 😄
