### ISSUE TITLE
FAQ: Is there a vue wrapper?

### ISSUE THREAD

**Issue by eric-g-97477** [mathuo/dockview#766]
The documentation says:

> Supports React, Vue and Vanilla TypeScript

The FAQ says:

> Are there any plans to publish wrapper libraries for other frameworks such as Angular and Vue?
> Currently no but this is open for contributors to try.

There does seem to be a vue wrapper at:

https://github.com/mathuo/dockview/tree/master/packages/dockview-vue

Can some clarification be provided? Is there an example using the vue wrapper?

**Comment by mathuo** [comment]
There is a vue wrapper yes, that particular piece of documentation is out of date and will be updated.

For live example see https://dockview.dev/templates/ and the code can be found at https://github.com/mathuo/dockview/tree/master/packages/docs/templates/dockview
