### ISSUE TITLE
packages/docs/sandboxes/javascript/simple-dockview is broken

### ISSUE THREAD

**Issue by eric-g-97477** [mathuo/dockview#767]
In the app.ts file there is:

```
    const dockview = new DockviewComponent({
        components: {
            default: DefaultPanel,
        },
        parentElement: element,
    });
```

However, DockviewComponent requires two arguments. 

I am not sure how to update the code so this will work again.

**Comment by mathuo** [comment]
That folder is no longer in use, up to date examples can be found at https://github.com/mathuo/dockview/tree/master/packages/docs/templates/dockview with live demos at https://dockview.dev/templates/

**Comment by mslxl** [comment]
Hello, the [ExampleFrame](https://github.com/mathuo/dockview/blob/88254df4699ac8c515930c5165650a4832d70f6e/packages/docs/src/components/ui/exampleFrame.tsx#L17) inside [demo page](https://github.com/mathuo/dockview/blob/88254df4699ac8c515930c5165650a4832d70f6e/packages/docs/src/pages/demo.tsx#L80-L85) still imports the component under sandboxes folder, is there a mistake?

Besides, the actiongroup of [react/demo-deckview](https://dockview.dev/templates/dockview/demo-dockview/react/index.html) seems not work
