### ISSUE TITLE
Keeping header actions even when no tabs are open

### ISSUE THREAD

**Issue by danielgoodwin97** [mathuo/dockview#777]
I'm currently running into an issue where I need to keep the header actions for a group/view even when there are no tabs.

I've found an example of someone doing something similar [here](https://github.com/mathuo/dockview/issues/84), but it's not completely applicable. Due to the fact that I need the menu button to be on the same line as the tabs themselves, which is why `prefixHeaderActionsComponent` and others are perfect for what I'm trying to do.

Here's an image of the current setup:
![image](https://github.com/user-attachments/assets/d505499e-5874-461c-bab7-a1651422e138)

Here's the desired outcome when closing the only tab:
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/a6d49510-88ea-44d9-98e8-7e68cc03b7a0">

Here's the reality (it's nothing, everything disappears)
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/8118d409-0be6-47a6-8b0d-14c2de63adde">

I've been combing through documentation for a while and haven't been able to find something that would help me for this. The only thing that I can think of is to make sure there's always a tab open by adding a invisible tab when there are no actual tabs open. I'm hoping this isn't the solution because it's gross.

Any help appreciated 🙏

**Comment by chhsgithub** [comment]
+1
