### ISSUE TITLE
Calling close() on a popout group will also close the group from which it originated

### ISSUE THREAD

**Issue by zaxer2** [mathuo/dockview#780]
**Describe the bug**
When addPopoutGroup is called with an IDockViewPanel as its parameter, it creates a new group that is inexplicably "bound" to the group from which that panel originated. When the new group is closed, the old group will be closed as well.

**To Reproduce**
This issue can be demonstrated with just the Dockview Demo codesandbox.

1. Go to https://codesandbox.io/p/sandbox/frosty-shtern-ldx2jk
2. Click "Open in New Window" on panel_3
3. Click "Close" on panel_3 OR call close() on the new group created for the popout window
4. Panels 1 and 2 will inexplicably close

**Expected behavior**
Panels 1 and 2 should remain, only panel 3 should close.

**Videos**
https://github.com/user-attachments/assets/cadaa47a-0816-4f03-acc3-f245a11a93b0

https://github.com/user-attachments/assets/dff2d581-e0bc-4568-a6e7-c88a978a210a

**Desktop (please complete the following information):**

 - Chrome
 - Version 131.0.6778.86
 - Dockview version 2.0.0

**Additional context**
I'm working on an app with controls that let the user pop out individual panels, in addition to whole groups, so this issue pops up extremely often.

**Comment by zaxer2** [comment]
To clarify I suppose, because I'm not sure I was descriptive enough: a prescient problem with the new Group that is generated after calling api.addPopoutGroup() with an IDockviewPanel as the parameter. Closing the new Group by any means will also close the old Group, even though these two groups should no longer be related in any way.

**Comment by zaxer2** [comment]
Currently- as a workaround- I call moveTo on the panel being moved before I pop it out. This puts it in its own group, so the original group doesn't get destroyed when the new group is Close()d.

https://github.com/user-attachments/assets/04d998f1-c183-4580-bbc6-a007a7ecb592

**Comment by zaxer2** [comment]
Currently- as a workaround- I call moveTo on the panel being moved before I pop it out. This puts it in its own group, so the original group doesn't get destroyed when the new group is Close()d. This is fine for now, if a little janky in appearance.👍

https://github.com/user-attachments/assets/5a655450-ac27-489e-8d92-4017c55e0097

**Comment by mathuo** [comment]
This should be fixed as of version `2.1.1`. Please do let me know if you agree

**Comment by zaxer2** [comment]
Yes, tested & fixed as of 2.1.1 - nice one! :)
