### ISSUE TITLE
class `dv-single-tab` not updated on drag & drop of tabs

### ISSUE THREAD

**Issue by amirmamaghani** [mathuo/dockview#784]
Class `dv-single-tab` is not updated (remove/added) to `tabs-and-actions-container` on changing tab count in group.

**Comment by amirmamaghani** [comment]
👀

**Comment by amirmamaghani** [comment]
any updates guys? @mathuo 🙏

**Comment by mathuo** [comment]
Sorry, this must have gotten lost. Raised a PR to fix with tests - will aim to release soon, just need to verify some additional changes first.

**Comment by mathuo** [comment]
Released in `3.0.0`
