### ISSUE TITLE
Save Example

### ISSUE THREAD

**Issue by JosephP91** [mathuo/dockview#9]
Hi! Can you provide an example of how can I save an entire workspace?

**Comment by mathuo** [comment]
Hi - please see this code sandbox example  https://codesandbox.io/s/workspace-saving-example-euo5d

The dockview ```api``` (exposed via the ```onReady(...)``` props on ```<DockviewReact/>``` exposes two methods to assist with serialization/de-serialization which are ```api.toJSON()``` and ```api.fromJSON(workspace)```.

You can save the contents of ```api.toJSON()``` and use this object to reload the workspace via ```api.fromJSON(workspace)```.

Note also the method ```api.onDidLayoutChange(...)``` which gives you an option to provide a callback method when the workspace state changes.

Hope this helps, let me know if you need anything more.

**Comment by JosephP91** [comment]
Hi! Thank you! Just tried those methods and they work like a charm! BTW, great project!
